### ISSUE TITLE
Broken BGEN link

### ISSUE THREAD

**Issue by valentinsulzer** [mkerin/LEMMA#1]
Link to the BGEN file format on this page https://mkerin.github.io/LEMMA/install/ is broken.

FYI, it's possible to set up automatic code checking for dead links, though I haven't tried this myself. See https://github.com/julia-actions/example-workflows/blob/master/.github/workflows/valid-links.yml

**Comment by mkerin** [comment]
Thank you for letting me know - this is now fixed.
