### ISSUE TITLE
LEMMA terminates after throwing an instance of 'std::regex_error'

### ISSUE THREAD

**Issue by shinichinamba** [mkerin/LEMMA#2]
Hello, I am excited to use your software, but have having difficulties with getting it running.

First, I found 'unit/test_hyps.cpp' requires 'src/tools/Eigen/Dense' instead of 'src/tools/eigen3.3/Dense', so I copied 'src/tools/eigen3.3' to 'src/tools/Eigen'.

After that, I could successfully compiled LEMMA with 
`cmake -S . -B build -DBGEN_ROOT=~/Softwares/bgen -DBOOST_ROOT=~/Softwares/boost_1_74_0/stage -DMKL_ROOT=/opt/inter/mkl`

However, when I run build/lemma_1_0_1, an error occurred;

`./lemma_1_0_1`
> ./lemma_1_0_1: error while loading shared libraries: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory

I found libmkl_intel_lp64.so are located at /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so, so I couldn't solve this error.

Then, I re-compiled LEMMA without -DMKL_ROOT option, and again lemma_1_0_1 was successfully built.
Nevertheless, LEMMA terminated immediately with the following message;

`./lemma_1_0_1`
> terminate called after throwing an instance of 'std::regex_error'
>   what(): regex_error
> Aborted

I additionally tried the second example code, 
`mpirun -n 1 build/lemma_1_0_1 \
  --VB \
  --pheno example/pheno.txt.gz \
  --environment example/env.txt.gz \
  --bgen example/n5k_p20k_example.bgen \
  --out example/inference.out.gz`

but again I got the same termination error.

(I could not find example/n5k_p20k_example_chr${cc}.bgen in the repository, so I could not try the first example code.)

Any advice would be appreciated.

===
My environment: CentOS7 on WSL2, cmake version 3.17.3, gcc version 4.8.5

**Comment by mkerin** [comment]
Hello,

Thank you for your detailed report.

The quick answer to your issue with `std::regex_error` is that I believe you need a newer GCC compiler (at least 4.9) for compatibility with std::regex. I will add a warning in the CMake file for this.

Going through your other comments in sequence:
(1) Good spot; I will update unit/test_hyps.cpp in my next commit.
(2) I will think about how best to resolve the intel mkl issue (it is not obvious to me at the moment).. but this is not critical for now.
(3) There is code to create `example/n5k_p20k_example_chr${cc}.bgen` locally in the installation guide. The for-loop is as follows
```
rm example/bgen_filenames.txt
for cc in `seq 1 22`; do
  bgenix -g example/n5k_p20k_example.bgen -incl-range ${cc}:0-1000000000 > example/n5k_p20k_example_chr${cc}.bgen;
  bgenix -index -g example/n5k_p20k_example_chr${cc}.bgen;
  echo "example/n5k_p20k_example_chr${cc}.bgen" >> example/bgen_filenames.txt;
done
```
but maybe this could be clearer.

**Comment by shinichinamba** [comment]
Thank you for your prompt reply.

After compiling with gcc 8.3.1, LEMMA worked fine!

I'm sorry for overlooking the code to create 'example/n5k_p20k_example_chr${cc}.bgen', and thank you for the kind guidance.
