### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by renhchung** [mkerin/LEMMA#3]
Hi,
I encountered this error during compilation:
[ 54%] Linking CXX executable lemma_1_0_1
CMakeFiles/lemma_1_0_1.dir/src/main.cpp.o: In function `Data::apply_filters()':
main.cpp:(.text._ZN4Data13apply_filtersEv[_ZN4Data13apply_filtersEv]+0x1ae): undefined reference to `genfile::bgen::IndexQuery::create(std::string const&, std::string const&)'
main.cpp:(.text._ZN4Data13apply_filtersEv[_ZN4Data13apply_filtersEv]+0x2bd): undefined reference to `genfile::bgen::IndexQuery::create(std::string const&, std::string const&)'
CMakeFiles/lemma_1_0_1.dir/src/main.cpp.o: In function `Data::Data(parameters&)':
main.cpp:(.text._ZN4DataC2ER10parameters[_ZN4DataC5ER10parameters]+0xa72): undefined reference to `genfile::bgen::View::create(std::string const&)'

Any ideas how to fix this? Thank you very much!

**Comment by mkerin** [comment]
Hi,

At the risk of stating the obvious, this looks like a linker error with the bgen library. LEMMA expects to find the BGEN library file at _${BGENROOT}/build/libbgen.a_ where ${BGENROOT} is the directory that you provided to help Cmake locate the bgen installation. You could start by checking manually to see if this files exists.

If that doesn't help then could you rerun the CMake build progress and attach the entire output as a text file to this issue. I'll then look through and see if I can suggest something more specific.

**Comment by mkerin** [comment]
Hi

Did you manage to resolve this issue?

**Comment by renhchung** [comment]
Yes, we did. Thanks for the help.
