### ISSUE TITLE
Issue with compilation of LEMMA

### ISSUE THREAD

**Issue by jeantristanb** [mkerin/LEMMA#7]
Dear Author,
I'm searching to compile LEMMA, but I have a compile issue :

/usr/bin/ld: /bgen.tgz/build/libbgen.a(bgen.cpp.3.o): undefined reference to symbol 'uncompress'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lemma_1_0_2.dir/build.make:274: lemma_1_0_2] Error 1
make[1]: *** [CMakeFiles/Makefile2:422: CMakeFiles/lemma_1_0_2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

I'm using a docker image and tested different bgen,

Code of docker image :
FROM ubuntu:16.04

ENV ver "0.94.1"

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN apt-get update && apt-get install -y wget  libboost-all-dev curl git python3-pip mpi libscalapack-mpi-dev zlib1g-dev
RUN apt-get -y install python-dev g++ build-essential autotools-dev libbz2-dev  libzstd-dev

RUN pip3 install --upgrade pip
RUN pip3 install cmake Cython

## test another bgen
#RUN curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=almosthere bash
#RUN curl -fsSL https://git.io/JerYI | GITHUB_USER=limix GITHUB_PROJECT=bgen bash

#RUN bash <(curl -fsSL https://raw.githubusercontent.com/horta/zstd.install/master/install)

RUN git clone https://github.com/limix/bgen.git && cd bgen && git checkout develop && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=On .. && cmake --build . --config Release

RUN tar -xzf bgen.tgz && cd bgen.tgz/ && ./waf configure && ./waf
RUN cd / && wget -c https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.gz && tar -xzf boost_1_74_0.tar.gz && cd boost_1_74_0 && ./bootstrap.sh && ./b2

RUN cd / && git clone https://github.com/mkerin/LEMMA
RUN cd /LEMMA/ && cmake -S . -B build \
    -DBGEN_ROOT=/bgen.tgz/  -DBOOST_ROOT=/boost_1_74_0/ && \
    cmake --build build -- -j4

**Comment by mkerin** [comment]
Apologies for taking so long to reply to this. For what it's worth - I have done some work in the latest release to make LEMMA easier to compile.
